// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package db

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin (name, email, cnpj,password)
VALUES (
           $1,
           $2,
        $3,
    $4
       )
RETURNING id, cnpj, name, email, password, created_at
`

type CreateAdminParams struct {
	Name     string
	Email    string
	Cnpj     string
	Password string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.Name,
		arg.Email,
		arg.Cnpj,
		arg.Password,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Cnpj,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const createLoginAdmin = `-- name: CreateLoginAdmin :one
SELECT name, email, password
FROM admin
WHERE email = $1
  AND password = $2
LIMIT 1
`

type CreateLoginAdminParams struct {
	Email    string
	Password string
}

type CreateLoginAdminRow struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateLoginAdmin(ctx context.Context, arg CreateLoginAdminParams) (CreateLoginAdminRow, error) {
	row := q.db.QueryRowContext(ctx, createLoginAdmin, arg.Email, arg.Password)
	var i CreateLoginAdminRow
	err := row.Scan(&i.Name, &i.Email, &i.Password)
	return i, err
}
