// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cadastro.sql

package db

import (
	"context"
	"database/sql"
)

const createCadastro = `-- name: CreateCadastro :one
INSERT INTO cadastro (name, cnpj, cpf,email, celular, password, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,now())
RETURNING id, name, cpf, cnpj, email, celular, password, status, activation_code, created_at
`

type CreateCadastroParams struct {
	Name     string
	Cnpj     sql.NullString
	Cpf      sql.NullString
	Email    string
	Celular  string
	Password string
	Status   string
}

func (q *Queries) CreateCadastro(ctx context.Context, arg CreateCadastroParams) (Cadastro, error) {
	row := q.db.QueryRowContext(ctx, createCadastro,
		arg.Name,
		arg.Cnpj,
		arg.Cpf,
		arg.Email,
		arg.Celular,
		arg.Password,
		arg.Status,
	)
	var i Cadastro
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Cnpj,
		&i.Email,
		&i.Celular,
		&i.Password,
		&i.Status,
		&i.ActivationCode,
		&i.CreatedAt,
	)
	return i, err
}

const getSellerByCNPJ = `-- name: GetSellerByCNPJ :one
SELECT id, name, email, celular, password, status, activation_code, created_at
FROM cadastro
WHERE celular= $1
`

type GetSellerByCNPJRow struct {
	ID             int64
	Name           string
	Email          string
	Celular        string
	Password       string
	Status         string
	ActivationCode sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) GetSellerByCNPJ(ctx context.Context, celular string) (GetSellerByCNPJRow, error) {
	row := q.db.QueryRowContext(ctx, getSellerByCNPJ, celular)
	var i GetSellerByCNPJRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Celular,
		&i.Password,
		&i.Status,
		&i.ActivationCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateActivationCode = `-- name: UpdateActivationCode :exec
UPDATE cadastro
SET activation_code = $2,
    status = $3
WHERE celular = $1
`

type UpdateActivationCodeParams struct {
	Celular        string
	ActivationCode sql.NullString
	Status         string
}

func (q *Queries) UpdateActivationCode(ctx context.Context, arg UpdateActivationCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateActivationCode, arg.Celular, arg.ActivationCode, arg.Status)
	return err
}

const updateCadastroStatus = `-- name: UpdateCadastroStatus :exec
UPDATE cadastro
SET status = $2
WHERE activation_code= $1
`

type UpdateCadastroStatusParams struct {
	ActivationCode sql.NullString
	Status         string
}

func (q *Queries) UpdateCadastroStatus(ctx context.Context, arg UpdateCadastroStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCadastroStatus, arg.ActivationCode, arg.Status)
	return err
}
