// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: login.sql

package db

import (
	"context"
)

const createLogin = `-- name: CreateLogin :one
INSERT INTO cadastro (email, password)
VALUES ($1, $2)
RETURNING id, name, cpf, cnpj, email, celular, password, status, activation_code, created_at
`

type CreateLoginParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateLogin(ctx context.Context, arg CreateLoginParams) (Cadastro, error) {
	row := q.db.QueryRowContext(ctx, createLogin, arg.Email, arg.Password)
	var i Cadastro
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Cnpj,
		&i.Email,
		&i.Celular,
		&i.Password,
		&i.Status,
		&i.ActivationCode,
		&i.CreatedAt,
	)
	return i, err
}

const getLogin = `-- name: GetLogin :one
SELECT email, password
FROM cadastro
WHERE email = $1
`

type GetLoginRow struct {
	Email    string
	Password string
}

func (q *Queries) GetLogin(ctx context.Context, email string) (GetLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getLogin, email)
	var i GetLoginRow
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}
