// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID        int64
	Cnpj      string
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}

type Cadastro struct {
	ID             int64
	Name           string
	Cpf            sql.NullString
	Cnpj           sql.NullString
	Email          string
	Celular        string
	Password       string
	Status         string
	ActivationCode sql.NullString
	CreatedAt      sql.NullTime
}

type Login struct {
	Email    string
	Password string
}

type Produto struct {
	IDRoupa     int64
	Categoria   string
	Tamanho     string
	Cores       sql.NullString
	TempoValor  sql.NullFloat64
	Status      sql.NullString
	Localizacao sql.NullString
}

type Token struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	Active    bool
	CreatedAt time.Time
	AccessID  int64
}
