// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: produtos.sql

package db

import (
	"context"
	"database/sql"
)

const atualizarProdutoByID = `-- name: AtualizarProdutoByID :one
UPDATE produto
SET categoria = $1,
    tamanho = $2,
    cores = $3,
    tempo_valor = $4,
    status = $5,
    localizacao = $6
WHERE id_roupa = $7
RETURNING id_roupa, categoria, tamanho, cores, tempo_valor, status, localizacao
`

type AtualizarProdutoByIDParams struct {
	Categoria   string
	Tamanho     string
	Cores       sql.NullString
	TempoValor  sql.NullFloat64
	Status      sql.NullString
	Localizacao sql.NullString
	IDRoupa     int64
}

func (q *Queries) AtualizarProdutoByID(ctx context.Context, arg AtualizarProdutoByIDParams) (Produto, error) {
	row := q.db.QueryRowContext(ctx, atualizarProdutoByID,
		arg.Categoria,
		arg.Tamanho,
		arg.Cores,
		arg.TempoValor,
		arg.Status,
		arg.Localizacao,
		arg.IDRoupa,
	)
	var i Produto
	err := row.Scan(
		&i.IDRoupa,
		&i.Categoria,
		&i.Tamanho,
		&i.Cores,
		&i.TempoValor,
		&i.Status,
		&i.Localizacao,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO produto (categoria, tamanho, cores, tempo_valor, status, localizacao)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_roupa
`

type CreateProductParams struct {
	Categoria   string
	Tamanho     string
	Cores       sql.NullString
	TempoValor  sql.NullFloat64
	Status      sql.NullString
	Localizacao sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Categoria,
		arg.Tamanho,
		arg.Cores,
		arg.TempoValor,
		arg.Status,
		arg.Localizacao,
	)
	var id_roupa int64
	err := row.Scan(&id_roupa)
	return id_roupa, err
}

const getProdutoByDisponibilidade = `-- name: GetProdutoByDisponibilidade :many
SELECT categoria, tamanho, cores
FROM produto
WHERE id_roupa = $1 AND status = $2 AND localizacao = $3
`

type GetProdutoByDisponibilidadeParams struct {
	IDRoupa     int64
	Status      sql.NullString
	Localizacao sql.NullString
}

type GetProdutoByDisponibilidadeRow struct {
	Categoria string
	Tamanho   string
	Cores     sql.NullString
}

func (q *Queries) GetProdutoByDisponibilidade(ctx context.Context, arg GetProdutoByDisponibilidadeParams) ([]GetProdutoByDisponibilidadeRow, error) {
	rows, err := q.db.QueryContext(ctx, getProdutoByDisponibilidade, arg.IDRoupa, arg.Status, arg.Localizacao)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProdutoByDisponibilidadeRow
	for rows.Next() {
		var i GetProdutoByDisponibilidadeRow
		if err := rows.Scan(&i.Categoria, &i.Tamanho, &i.Cores); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProdutoById = `-- name: GetProdutoById :one
SELECT id_roupa,categoria, tamanho, cores, localizacao, tempo_valor, status
FROM produto
WHERE id_roupa = $1
`

type GetProdutoByIdRow struct {
	IDRoupa     int64
	Categoria   string
	Tamanho     string
	Cores       sql.NullString
	Localizacao sql.NullString
	TempoValor  sql.NullFloat64
	Status      sql.NullString
}

func (q *Queries) GetProdutoById(ctx context.Context, idRoupa int64) (GetProdutoByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getProdutoById, idRoupa)
	var i GetProdutoByIdRow
	err := row.Scan(
		&i.IDRoupa,
		&i.Categoria,
		&i.Tamanho,
		&i.Cores,
		&i.Localizacao,
		&i.TempoValor,
		&i.Status,
	)
	return i, err
}

const inativarProdutoByID = `-- name: InativarProdutoByID :exec
UPDATE produto
SET status = 'inativo'
WHERE id_roupa = $1
`

func (q *Queries) InativarProdutoByID(ctx context.Context, idRoupa int64) error {
	_, err := q.db.ExecContext(ctx, inativarProdutoByID, idRoupa)
	return err
}

const listProducts = `-- name: ListProducts :many
SELECT id_roupa, categoria, tamanho, cores, tempo_valor, status, localizacao
FROM produto
WHERE status ='Disponível'
`

func (q *Queries) ListProducts(ctx context.Context) ([]Produto, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Produto
	for rows.Next() {
		var i Produto
		if err := rows.Scan(
			&i.IDRoupa,
			&i.Categoria,
			&i.Tamanho,
			&i.Cores,
			&i.TempoValor,
			&i.Status,
			&i.Localizacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
