// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package db

import (
	"context"
	"time"
)

const createTokenHist = `-- name: CreateTokenHist :exec
INSERT INTO public.token
(id, user_id, "token", expires_at, active, created_at,access_id)
VALUES(nextval('token'::regclass), $1, $2, $3,true, now(), $4)
`

type CreateTokenHistParams struct {
	UserID    int64
	Token     string
	ExpiresAt time.Time
	AccessID  int64
}

func (q *Queries) CreateTokenHist(ctx context.Context, arg CreateTokenHistParams) error {
	_, err := q.db.ExecContext(ctx, createTokenHist,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.AccessID,
	)
	return err
}

const getUserTokensHist = `-- name: GetUserTokensHist :one
SELECT id, "token", expires_at, active
FROM public.token
WHERE user_id=$1 AND
    access_id=$2
`

type GetUserTokensHistParams struct {
	UserID   int64
	AccessID int64
}

type GetUserTokensHistRow struct {
	ID        int64
	Token     string
	ExpiresAt time.Time
	Active    bool
}

func (q *Queries) GetUserTokensHist(ctx context.Context, arg GetUserTokensHistParams) (GetUserTokensHistRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTokensHist, arg.UserID, arg.AccessID)
	var i GetUserTokensHistRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}
